In [1]:
import pandas as pd

In [15]:
df = pd.read_csv("../data/final/medicine_details_full.csv")
df.head()

,url,name,marketer,composition,uses,side_effects,image_url
0,https://www.1mg.com/drugs/cardiomart-h-40mg-12...,Cardiomart H 40mg/12.5mg Tablet,NaN,Telmisartan (40mg) + Hydrochlorothiazide (12.5mg),Treatment of Hypertension (high blood pressure...,Most side effects do not require any medical a...,"https://onemg.gumlet.io/q_auto,f_auto/iw8eipow..."
1,https://www.1mg.com/drugs/rosumart-10mg-tablet...,Rosumart 10mg Tablet,NaN,Rosuvastatin (10mg),Treatment of High cholesterol Treatment of Hig...,Most side effects do not require any medical a...,"https://onemg.gumlet.io/q_auto,f_auto/iw8eipow..."
2,https://www.1mg.com/drugs/tendonil-p-100mg-325...,Tendonil P 100mg/325mg Tablet,NaN,Aceclofenac (100mg) + Paracetamol (325mg),Pain relief In Pain relief Tendonil P 100mg/32...,Most side effects do not require any medical a...,"https://onemg.gumlet.io/q_auto,f_auto/iw8eipow..."
3,https://www.1mg.com/drugs/xenoten-cv-200mg-125...,Xenoten CV 200mg/125mg Tablet,NaN,Cefpodoxime Proxetil (200mg) + Clavulanic Acid...,Treatment of Respiratory tract infection In Tr...,Most side effects do not require any medical a...,"https://onemg.gumlet.io/q_auto,f_auto/iw8eipow..."
4,https://www.1mg.com/drugs/zomart-it-20mg-150mg...,Zomart IT 20mg/150mg Tablet SR,NaN,Rabeprazole (20mg) + Itopride (150mg),Treatment of Gastroesophageal reflux disease (...,Most side effects do not require any medical a...,"https://onemg.gumlet.io/q_auto,f_auto/iw8eipow..."

In [16]:
marketers = pd.read_csv("../data/raw/medicines_drugs_only.csv")
marketers.head()

,marketer,medicine_name,medicine_url
0,10 Drug Mart,Cardiomart H 40mg/12.5mg Tablet,https://www.1mg.com/drugs/cardiomart-h-40mg-12...
1,10 Drug Mart,Rosumart 10mg Tablet,https://www.1mg.com/drugs/rosumart-10mg-tablet...
2,10 Drug Mart,Tendonil P 100mg/325mg Tablet,https://www.1mg.com/drugs/tendonil-p-100mg-325...
3,10 Drug Mart,Xenoten CV 200mg/125mg Tablet,https://www.1mg.com/drugs/xenoten-cv-200mg-125...
4,10 Drug Mart,Zomart IT 20mg/150mg Tablet SR,https://www.1mg.com/drugs/zomart-it-20mg-150mg...

In [17]:
df["url"].head()
marketers["medicine_url"].head()

0    https://www.1mg.com/drugs/cardiomart-h-40mg-12...
1    https://www.1mg.com/drugs/rosumart-10mg-tablet...
2    https://www.1mg.com/drugs/tendonil-p-100mg-325...
3    https://www.1mg.com/drugs/xenoten-cv-200mg-125...
4    https://www.1mg.com/drugs/zomart-it-20mg-150mg...
Name: medicine_url, dtype: object

In [18]:
set(df["url"]) == set(marketers["medicine_url"])

False

In [19]:
len(set(df["url"]) & set(marketers["medicine_url"]))

226709

In [20]:
len(df), len(marketers)

(226716, 226744)

In [21]:
only_in_df = len(set(df["url"]) - set(marketers["medicine_url"]))
only_in_marketers = len(set(marketers["medicine_url"]) - set(df["url"]))

only_in_df, only_in_marketers

(0, 35)

In [23]:
print(226706 / len(df))

0.9999558919529279

In [24]:
df = df.merge(
    marketers[["medicine_url", "marketer"]],
    left_on="url",
    right_on="medicine_url",
    how="left"
)

df.drop(columns=["medicine_url"], inplace=True)

In [27]:
df.head()

,url,name,composition,uses,side_effects,image_url,marketer
0,https://www.1mg.com/drugs/cardiomart-h-40mg-12...,Cardiomart H 40mg/12.5mg Tablet,Telmisartan (40mg) + Hydrochlorothiazide (12.5mg),Treatment of Hypertension (high blood pressure...,Most side effects do not require any medical a...,"https://onemg.gumlet.io/q_auto,f_auto/iw8eipow...",10 Drug Mart
1,https://www.1mg.com/drugs/rosumart-10mg-tablet...,Rosumart 10mg Tablet,Rosuvastatin (10mg),Treatment of High cholesterol Treatment of Hig...,Most side effects do not require any medical a...,"https://onemg.gumlet.io/q_auto,f_auto/iw8eipow...",10 Drug Mart
2,https://www.1mg.com/drugs/tendonil-p-100mg-325...,Tendonil P 100mg/325mg Tablet,Aceclofenac (100mg) + Paracetamol (325mg),Pain relief In Pain relief Tendonil P 100mg/32...,Most side effects do not require any medical a...,"https://onemg.gumlet.io/q_auto,f_auto/iw8eipow...",10 Drug Mart
3,https://www.1mg.com/drugs/xenoten-cv-200mg-125...,Xenoten CV 200mg/125mg Tablet,Cefpodoxime Proxetil (200mg) + Clavulanic Acid...,Treatment of Respiratory tract infection In Tr...,Most side effects do not require any medical a...,"https://onemg.gumlet.io/q_auto,f_auto/iw8eipow...",10 Drug Mart
4,https://www.1mg.com/drugs/zomart-it-20mg-150mg...,Zomart IT 20mg/150mg Tablet SR,Rabeprazole (20mg) + Itopride (150mg),Treatment of Gastroesophageal reflux disease (...,Most side effects do not require any medical a...,"https://onemg.gumlet.io/q_auto,f_auto/iw8eipow...",10 Drug Mart

In [26]:
# Drop old empty column
df.drop(columns=["marketer_x"], inplace=True)

# Rename merged column
df.rename(columns={"marketer_y": "marketer"}, inplace=True)

In [28]:
df["marketer"].isna().mean()

np.float64(0.0)

In [29]:
def clean_text(x):
    if pd.isna(x):
        return x
    return " ".join(x.split())

df["uses"] = df["uses"].apply(clean_text)
df["side_effects"] = df["side_effects"].apply(clean_text)

In [30]:
import re

def parse_composition(comp):
    if pd.isna(comp):
        return []
    return re.findall(r'([A-Za-z]+)\s*\(([\d\.]+mg)\)', comp)

df["composition_parsed"] = df["composition"].apply(parse_composition)

In [31]:
df.drop_duplicates(subset=["url"], inplace=True)

In [32]:
df.isna().mean().sort_values(ascending=False)

side_effects          0.017891
uses                  0.000101
composition           0.000004
name                  0.000004
image_url             0.000004
url                   0.000000
marketer              0.000000
composition_parsed    0.000000
dtype: float64

In [33]:
df["side_effects"] = df["side_effects"].fillna("Not available")

In [34]:
df.to_csv("../data/final/medicine_final_clean.csv", index=False)